### ISSUE TITLE
'No Decode Delegate Error' when running 'convert_images_to_monochrome.sh'

### ISSUE THREAD

**Issue by mattekey** [oboyone/mb_thermal_printer#3]
I'm running the sh script in an ubuntu virtual machine with Image Magick installed and keep getting this error. Looked for troubleshooting steps and tried re-installing IM to no avail. Any ideas what I'm doing wrong?

Very excited about the project!

**Comment by oboyone** [comment]
If you run "identify -list format" do you have both jpeg and bmp listed? 

"This exception indicates that an external delegate library or its headers were not available when ImageMagick was built.  To add support for the image format, download and install the requisite delegate library and its header files and reconfigure, rebuild, and reinstall ImageMagick."

**Comment by mattekey** [comment]
Got it working, thanks! =JPG was missing, these steps helped: https://gist.github.com/nickferrando/fb0a44d707c8c3efd92dedd0f79d2911

**Comment by oboyone** [comment]
Nice, good luck with your printer!
